import React from "react";
import Navbar from "./Navbar";


function Core() {

    return ( 

        <body id ="core-page">
                <Navbar/>
            <div className= "core--container">
            <h1 className ="core--title">CORE</h1>
            <p className ="core--dialogue1">IT IS HARD TO REMAIN UNMOVED BY THE THOUGHT ASSOCIATED WITH CREATION OF SOMETHING THAT ONE REGARDS AS ESSENTIAL, ESPECIALLY WHEN THE PRESENT WORLD HAS A DISPENSATION OF SUCH POWERFUL TOOLS TO CREATE.</p>
            <p className ="core--dialogue2">I HAVE ALWAYS BEEN CURIOUS ABOUT HOW THINGS OPERATE AT ELEMENTARY LEVEL WHICH OFTEN HELP US IN UNDERSTANDING THE MACRO. MY ADMIRATION FOR THE SOPHISTICATION STEMS FROM MY OBSERVATION OF MY SURROUNDINGS, THANKS TO MY CURIOSITY WHICH ENABLED ME TO TAKE A DEEP DIVE INTO WHAT IS UNKNOWN TO ME. MOREOVER THROUGH MY EXPERIENCES I HAVE LEARNT THAT A CLEAR UNDERSTANDING OF THE SUBJECT COULD BE VERIFIED BY A POTENTIAL MANIFESTATION OF A MUCH SIMPLER VIEW OF IT WHICH COULD BE USED TO IMPART KNOWLEDGE TO OTHERS, HEREIN GOOD DESIGN MAY COME TO THE AID, IN THIS PROCESS OF SIMPLIFICATION, WHERE NOTHING ESSENTIAL IS REMOVED ONLY BETTER MANAGED.</p>
            </div>

        </body>
    )
}
export default Core;