



// eslint-disable-next-line import/no-anonymous-default-export
export default [
    {
        id:1,
        coverImg: "tenziesgame.jpg" ,
        title: "Tenzies Game",
        description: " A simple game made with javascript and react",
        url:"https://guyfromhills.github.io/tenzies-game/"
    },

    {
        id:2,
        coverImg: "memegenerator.JPG" ,
        title: "Meme Generator",
        description: "Generate random memes and spread fun 😈",
        url:"https://guyfromhills.github.io/meme-template-generator/"

    },

    {
        id:3,
        coverImg: "speechsynthesis.jpg" ,
        title: "Speech Synthesis",
        description: "Generate speech of input text in different voices",
        url:"https://guyfromhills.github.io/Speech-Synthesis-23-vanilla_JS_challenge/"

    },

    {
        id:4,
        coverImg: "nativespeechrecognition.jpg" ,
        title: "Native Speech Recognition",
        description: "A speech to text project",
        url:"https://guyfromhills.github.io/Native-Speech-Recognition-20-vanilla_JS_challenge/"

    },

    
    {
        id:5,
        coverImg: "anubhav-logo.png" ,
        title: "Anubhav Negi",
        description: "My personal creative space",
        url:"https://guyfromhills.github.io/personal-website"

    },

    {
        id:6,
        coverImg: "light-dark-theme.jpg" ,
        title: "React Light & Dark",
        description: "A simple app incorporating light and dark themes",
        url:"https://guyfromhills.github.io/light-dark-theme-feature-app/"

    },
    {
        id:7,
        coverImg: "noise-flow-field.jpg" ,
        title: "Noise Flow Field",
        description: "A noise flow field generated by particles.",
        url:"https://openprocessing.org/sketch/1270616"

    },
    {
        id:8,
        coverImg: "netflix-clone-landing-page.jpg" ,
        title: "Netflix Clone",
        description: "A netlfix clone made purely with HTML, CSS and javascript",
        url:"https://guyfromhills.github.io/Netflix-Landing-Page-Clone/"

    }
]
